Updated deb files

diff --git a/debian/solydxk-system.postinst b/debian/solydxk-system.postinst
--- a/debian/solydxk-system.postinst
+++ b/debian/solydxk-system.postinst
@@ -39,6 +39,23 @@ fi
 # Automatically added by dh_installsystemd/13.3.4
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
+	deb-systemd-helper unmask 'solydxk-root-gtk3.service' >/dev/null || true
+
+	# was-enabled defaults to true, so new installations run enable.
+	if deb-systemd-helper --quiet was-enabled 'solydxk-root-gtk3.service'; then
+		# Enables the unit on first installation, creates new
+		# symlinks on upgrades if the unit file has changed.
+		deb-systemd-helper enable 'solydxk-root-gtk3.service' >/dev/null || true
+	else
+		# Update the statefile to add new symlinks (if any), which need to be
+		# cleaned up on purge. Also remove old symlinks.
+		deb-systemd-helper update-state 'solydxk-root-gtk3.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installsystemd/13.3.4
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'solydxk-system-aptupdate.service' >/dev/null || true
 
 	# was-enabled defaults to true, so new installations run enable.
@@ -62,7 +79,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 		else
 			_dh_action=start
 		fi
-		deb-systemd-invoke $_dh_action 'solydxk-cifs-umount.service' 'solydxk-system-aptupdate.service' >/dev/null || true
+		deb-systemd-invoke $_dh_action 'solydxk-cifs-umount.service' 'solydxk-minissdpd.service' 'solydxk-root-gtk3.service' 'solydxk-system-aptupdate.service' >/dev/null || true
 	fi
 fi
 # End automatically added section
