mount efivars

diff --git a/usr/bin/chroot-partition b/usr/bin/chroot-partition
--- a/usr/bin/chroot-partition
+++ b/usr/bin/chroot-partition
@@ -5,7 +5,7 @@ PASSPHRASE=$2
 COMMANDS=$3
 TARGET='/target'
 
-if [ -z $PARTITION ] || [ ! -e $PARTITION ]; then
+if [ -z ${PARTITION} ] || [ ! -e ${PARTITION} ]; then
   echo "An existing OS partition path or directory is needed"
   echo "E.g.: $0 /dev/sda1"
   echo "or: $0 /path/to/systemdir"
@@ -30,86 +30,88 @@ fi
 # Check if partition is already mounted and use that as the target
 if [ "${PARTITION:0:4}" == '/dev' ]; then
     # Map luks encrypted partition
-    FS=$(blkid -s TYPE -o value $PARTITION)
+    FS=$(blkid -s TYPE -o value ${PARTITION})
     if [ "$FS" == 'crypto_LUKS' ]; then
-        echo "Map encrypted partition $PARTITION"
-        PNAME=$(basename $PARTITION)
-        if [ "$PASSPHRASE" != '' ]; then
-            printf "$PASSPHRASE" | cryptsetup open --type luks $PARTITION $PNAME
+        echo "Map encrypted partition ${PARTITION}"
+        PNAME=$(basename ${PARTITION})
+        if [ ! -z ${PASSPHRASE} ]; then
+            printf "${PASSPHRASE}" | cryptsetup open --type luks ${PARTITION} ${PNAME}
         else
-            cryptsetup open --type luks $PARTITION $PNAME
+            cryptsetup open --type luks ${PARTITION} ${PNAME}
         fi
-        if [ ! -e "/dev/mapper/$PNAME" ]; then
-            echo "Unable to map encrypted partition $PARTITION - exiting"
+        if [ ! -e "/dev/mapper/${PNAME}" ]; then
+            echo "Unable to map encrypted partition ${PARTITION} - exiting"
             exit
         fi
-        PARTITION="/dev/mapper/$PNAME"
+        PARTITION="/dev/mapper/${PNAME}"
     fi
 
-    MOUNTCHK=$(grep "$PARTITION " /proc/mounts | awk '{print $2}')
-    if [ "$MOUNTCHK" != "" ]; then
-        TARGET=$MOUNTCHK
+    MOUNTCHK=$(grep "${PARTITION} " /proc/mounts | awk '{print $2}')
+    if [ "${MOUNTCHK}" != "" ]; then
+        TARGET=${MOUNTCHK}
     fi
     
     # Check if target is used as mount point by anything other than partition
-    MOUNTCHK=$(grep " $TARGET " /proc/mounts | grep -v "$PARTITION")
-    if [ "$MOUNTCHK" != "" ]; then
-        echo "$TARGET in use - exiting"
+    MOUNTCHK=$(grep " ${TARGET} " /proc/mounts | grep -v "${PARTITION}")
+    if [ ! -z ${MOUNTCHK} ]; then
+        echo "${TARGET} in use - exiting"
         exit 1
     fi
     
     # Create temporary dir
-    if [ ! -d "$TARGET" ]; then
-        mkdir -v "$TARGET"
+    if [ ! -d ${TARGET} ]; then
+        mkdir -v ${TARGET}
     fi
     
     # Mounting
-    mount -v $PARTITION "$TARGET"
+    mount -v ${PARTITION} ${TARGET}
 else
     # No partition but directory is provided
-    TARGET=$PARTITION
+    TARGET=${PARTITION}
 fi
 
-if [ ! -d "$TARGET"/dev ] || [ ! -d "$TARGET"/proc ] || [ ! -d "$TARGET"/sys ] || [ ! -d "$TARGET"/run ]; then
-    echo "Missing $TARGET/{dev,proc,sys,run} - exiting"
-    if [ "$TARGET" == "/target" ]; then
-        umount -v "$TARGET"
-        rmdir -v "$TARGET"
+if ! $(ls ${TARGET}{/run,/sys,/proc,/dev} >/dev/null 2>&1); then
+    echo "Missing ${TARGET}/{dev,proc,sys,run} - exiting"
+    if [ ${TARGET} == "/target" ]; then
+        umount -v ${TARGET}
+        rmdir -v ${TARGET}
     fi
     exit 2
 fi
 
-# Make nodes and bind directories
-mknod -m 600 "$TARGET"/dev/console c 5 1 2>/dev/null
-mknod -m 666 "$TARGET"/dev/null c 1 3 2>/dev/null
-mount -v --bind /dev "$TARGET"/dev
-mount -vt devpts devpts "$TARGET"/dev/pts -o gid=5,mode=620
-mount -vt proc proc "$TARGET"/proc
-mount -vt sysfs sysfs "$TARGET"/sys
-mount -vt tmpfs tmpfs "$TARGET"/run
-if [ -h "$TARGET"/dev/shm ]; then mkdir -pv "$TARGET"/$(readlink "$TARGET"/dev/shm); fi
-if [ -h "$TARGET"/var/lock ]; then mkdir -pv "$TARGET"/$(readlink "$TARGET"/var/lock); fi
+# Bind directories
+mount -vt devtmpfs devtmpfs ${TARGET}/dev
+mount -vt devpts devpts ${TARGET}/dev/pts
+mount -vt proc proc ${TARGET}/proc
+mount -vt sysfs sysfs ${TARGET}/sys
+mount -vt tmpfs tmpfs ${TARGET}/run
+if [ -d /sys/firmware/efi/efivars ] && 
+   [ -d ${TARGET}/sys/firmware/efi/efivars ]; then
+    mount -vt efivarfs efivarfs ${TARGET}/sys/firmware/efi/efivars
+fi
+if [ -h ${TARGET}/dev/shm ]; then mkdir -pv ${TARGET}/$(readlink ${TARGET}/dev/shm); fi
+if [ -h ${TARGET}/var/lock ]; then mkdir -pv ${TARGET}/$(readlink ${TARGET}/var/lock); fi
 
 # Mount all partitions in the chrooted fstab
-chroot "$TARGET"/ /bin/bash -c "mount -av 2>/dev/null"
+chroot ${TARGET}/ /bin/bash -c "mount -av 2>/dev/null"
 
 # Chroot into dir
-echo "Chrooting into $TARGET..."
-if [ ! -z "$COMMANDS" ]; then COMMANDS="-c \"$COMMANDS\""; fi
+echo "Chrooting into ${TARGET}..."
+if [ ! -z ${COMMANDS} ]; then COMMANDS="-c \"${COMMANDS}\""; fi
 
-eval "chroot \"$TARGET\" /usr/bin/env -i \
+eval "chroot \"${TARGET}\" /usr/bin/env -i \
     HOME=/root \
     TERM=\"$TERM\" \
     PS1='(chroot) \u:\w\\$ ' \
     PATH=/bin:/usr/bin:/sbin:/usr/sbin \
     /bin/bash --login +h \
-    $COMMANDS"
+    ${COMMANDS}"
 
 # Unmount when done
-umount -v "$TARGET"/{run,sys,proc,dev/pts,dev}
-grep "$TARGET" /proc/mounts | grep ^/dev | grep -v "$PARTITION" | awk '{print $1}' | xargs umount -v 2>/dev/null
+umount -v ${TARGET}/{run,sys/firmware/efi/efivars,sys,proc,dev/pts,dev}
+grep ${TARGET} /proc/mounts | grep ^/dev | grep -v "${PARTITION}" | awk '{print $1}' | xargs umount -v 2>/dev/null
 
-if [ "$TARGET" == "/target" ]; then
-    umount -lfv "$TARGET"
-    rmdir -v "$TARGET" 2>/dev/null
+if [ ${TARGET} == "/target" ]; then
+    umount -lfv ${TARGET}
+    rmdir -v ${TARGET} 2>/dev/null
 fi
